"""
Session output generator for TechLens.

Produces the three end-of-session documents:
  1. Tech Notes  — detailed diagnostic findings for the shop file
  2. Customer Summary — plain-language explanation for the RO
  3. Escalation Brief — structured handoff for senior tech or service advisor
"""

import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def generate_session_outputs(
    transcript: str,
    findings: list,
    vehicle: dict,
) -> dict:
    """
    Generate the three TechLens session output documents.

    In production this function calls Gemini to produce polished,
    context-aware documents. The current implementation returns
    structured placeholder templates that wire up correctly to the
    frontend rendering layer.

    Args:
        transcript: Full text transcript of the technician session.
        findings:   List of finding dicts, each with keys:
                      - system (str): e.g. "CVT", "Engine", "Brakes"
                      - description (str): what was observed or measured
                      - severity (str): "info" | "warning" | "critical"
        vehicle:    Vehicle info dict as returned by lookup_vehicle_info().

    Returns:
        dict with keys:
          - tech_notes (str): Detailed technical findings for the shop file
          - customer_summary (str): Plain-language explanation for the customer
          - escalation_brief (str): Structured handoff for SA or senior tech
          - generated_at (str): ISO 8601 timestamp
          - vehicle_summary (str): One-line vehicle description
    """
    year = vehicle.get("year", "Unknown")
    make = vehicle.get("make", "Unknown")
    model = vehicle.get("model", "Unknown")
    vehicle_summary = f"{year} {make} {model}"
    generated_at = datetime.now(timezone.utc).isoformat()

    # Build findings section
    findings_lines = []
    for i, finding in enumerate(findings, start=1):
        system = finding.get("system", "General")
        description = finding.get("description", "No description provided.")
        severity = finding.get("severity", "info").upper()
        findings_lines.append(f"  [{severity}] {i}. {system}: {description}")
    findings_text = "\n".join(findings_lines) if findings_lines else "  No structured findings recorded."

    # ── 1. Tech Notes ──────────────────────────────────────────────────────────
    tech_notes = f"""TECHLENS SESSION — TECH NOTES
{'=' * 60}
Vehicle:     {vehicle_summary}
Generated:   {generated_at}

TRANSCRIPT SUMMARY
------------------
{transcript.strip() if transcript else '[No transcript captured]'}

DIAGNOSTIC FINDINGS
-------------------
{findings_text}

NEXT STEPS
----------
[TODO — Gemini will populate recommended repairs, part numbers,
 labor times, and reference TSBs when production integration is complete]

NOTES
-----
Generated by TechLens AI diagnostic assistant.
Technician should review and verify all findings before committing to RO.
"""

    # ── 2. Customer Summary ────────────────────────────────────────────────────
    customer_summary = f"""SERVICE VISIT SUMMARY
{'=' * 60}
Vehicle: {vehicle_summary}
Date:    {generated_at[:10]}

Thank you for bringing your {vehicle_summary} in today.

During our diagnostic session, our technician identified the following:

{findings_text}

[TODO — Gemini will generate a plain-language customer-friendly explanation
 of each finding, what it means for safety and reliability, and a clear
 recommendation on repair priority when production integration is complete]

If you have any questions about these findings, please speak with your
service advisor. We appreciate your business!
"""

    # ── 3. Escalation Brief ────────────────────────────────────────────────────
    critical_findings = [
        f for f in findings if f.get("severity", "").lower() == "critical"
    ]
    warning_findings = [
        f for f in findings if f.get("severity", "").lower() == "warning"
    ]

    escalation_brief = f"""ESCALATION BRIEF — TECHLENS
{'=' * 60}
Vehicle:     {vehicle_summary}
Timestamp:   {generated_at}
Priority:    {'🔴 CRITICAL' if critical_findings else '🟡 REVIEW NEEDED' if warning_findings else '🟢 ROUTINE'}

CRITICAL ITEMS ({len(critical_findings)})
{'-' * 40}
{''.join(f"  • [{f.get('system','?')}] {f.get('description','')}\n" for f in critical_findings) or '  None'}

WARNINGS ({len(warning_findings)})
{'-' * 40}
{''.join(f"  • [{f.get('system','?')}] {f.get('description','')}\n" for f in warning_findings) or '  None'}

SESSION CONTEXT
{'-' * 40}
{transcript[:500].strip() if transcript else '[No transcript]'}{'...' if len(transcript or '') > 500 else ''}

[TODO — Gemini will populate recommended escalation path, parts pre-order
 suggestions, and flag warranty/recall applicability when production
 integration is complete]

--- End of TechLens Escalation Brief ---
"""

    return {
        "tech_notes": tech_notes,
        "customer_summary": customer_summary,
        "escalation_brief": escalation_brief,
        "generated_at": generated_at,
        "vehicle_summary": vehicle_summary,
    }
