"""
Session output generator for TechLens.

Produces the three end-of-session documents:
  1. Tech Notes  — detailed diagnostic findings for the shop file
  2. Customer Summary — plain-language explanation for the RO
  3. Escalation Brief — structured handoff for senior tech or service advisor
"""

import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def generate_session_outputs(
    transcript: str,
    findings: list[str],
    vehicle_summary: str,
) -> dict:
    """
    Generate the three TechLens session output documents.

    In production this function calls Gemini to produce polished,
    context-aware documents. The current implementation returns
    structured placeholder templates that wire up correctly to the
    frontend rendering layer.

    Args:
        transcript: Full text transcript of the technician session.
        findings:   List of diagnostic finding strings, e.g.
                    ["Torn CV boot passenger side", "CVT fluid dark, needs replace"]
        vehicle_summary: One-line vehicle description, e.g. "2024 Subaru Outback"

    Returns:
        dict with keys:
          - tech_notes (str): Detailed technical findings for the shop file
          - customer_summary (str): Plain-language explanation for the customer
          - escalation_brief (str): Structured handoff for SA or senior tech
          - generated_at (str): ISO 8601 timestamp
          - vehicle_summary (str): One-line vehicle description
    """
    generated_at = datetime.now(timezone.utc).isoformat()

    # Build findings section
    findings_lines = []
    for i, finding in enumerate(findings, start=1):
        findings_lines.append(f"  {i}. {finding}")
    findings_text = "\n".join(findings_lines) if findings_lines else "  No structured findings recorded."

    # ── 1. Tech Notes ──────────────────────────────────────────────────────────
    tech_notes = f"""TECHLENS SESSION — TECH NOTES
{'=' * 60}
Vehicle:     {vehicle_summary}
Generated:   {generated_at}

TRANSCRIPT SUMMARY
------------------
{transcript.strip() if transcript else '[No transcript captured]'}

DIAGNOSTIC FINDINGS
-------------------
{findings_text}

NEXT STEPS
----------
[TODO — Gemini will populate recommended repairs, part numbers,
 labor times, and reference TSBs when production integration is complete]

NOTES
-----
Generated by TechLens AI diagnostic assistant.
Technician should review and verify all findings before committing to RO.
"""

    # ── 2. Customer Summary ────────────────────────────────────────────────────
    customer_summary = f"""SERVICE VISIT SUMMARY
{'=' * 60}
Vehicle: {vehicle_summary}
Date:    {generated_at[:10]}

Thank you for bringing your {vehicle_summary} in today.

During our diagnostic session, our technician identified the following:

{findings_text}

[TODO — Gemini will generate a plain-language customer-friendly explanation
 of each finding, what it means for safety and reliability, and a clear
 recommendation on repair priority when production integration is complete]

If you have any questions about these findings, please speak with your
service advisor. We appreciate your business!
"""

    # ── 3. Escalation Brief ────────────────────────────────────────────────────
    escalation_brief = f"""ESCALATION BRIEF — TECHLENS
{'=' * 60}
Vehicle:     {vehicle_summary}
Timestamp:   {generated_at}

FINDINGS
{'-' * 40}
{findings_text}

SESSION CONTEXT
{'-' * 40}
{transcript[:500].strip() if transcript else '[No transcript]'}{'...' if len(transcript or '') > 500 else ''}

--- End of TechLens Escalation Brief ---
"""

    return {
        "tech_notes": tech_notes,
        "customer_summary": customer_summary,
        "escalation_brief": escalation_brief,
        "generated_at": generated_at,
        "vehicle_summary": vehicle_summary,
    }
